name: build / test / release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: sudo apt install hunspell

    - name: build
      run: make

    - name: test
      run: make test

    - name: build dist
      if: startsWith(github.ref, 'refs/tags/')
      run: make bdist

    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/ko-*.zip
